name: Build Windows EXE

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt 6
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.2'
          modules: 'qt5compat'

      - name: Build Project
        env:
          CL: "/D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS /D_SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING /D_SCL_SECURE_NO_WARNINGS"
          CXXFLAGS: "/D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS /D_SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING /D_SCL_SECURE_NO_WARNINGS"
        run: cargo build --release

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: FortuneWheel-Windows-EXE
          path: target/release/*.exe